name = "server"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"
DATABASE_URL="postgresql://sarthaksanjaycoll21:uFsaGK2N8Udi@ep-crimson-sky-00140653.us-east-2.aws.neon.tech/cohort2test?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
