-- AlterTable
ALTER TABLE "Comment" ADD COLUMN     "bookmarks" INTEGER DEFAULT 0,
ADD COLUMN     "commentCount" INTEGER DEFAULT 0,
ADD COLUMN     "createOn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "likes" INTEGER DEFAULT 0,
ADD COLUMN     "reposts" INTEGER DEFAULT 0,
ADD COLUMN     "views" INTEGER DEFAULT 0;
